apiVersion: v1
kind: Service
metadata:
  name: llm-backend-stable-svc
spec:
  selector:
    app: llm-backend
    version: stable
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
